### ISSUE TITLE
likelyhood to get banned

### ISSUE THREAD

**Issue by TheIngster** [casid/poe-stash-buddy#2]
Hi Dev,
Looks like its been a few years since you created this. Have you been using it without getting banned?

**Comment by casid** [comment]
I'm not playing that much anymore, but I've been using it casually on every league start until my HC char eventually dies, without getting banned.

**Comment by TheIngster** [comment]
Awesome, thanks for the quick reply. I've also been having some trouble getting it to work on 2560x1440p
I believe I've done the area correct however its clicking just a little bit off. When I try to adjust its still not happy. Any chance you can assist?

**Comment by casid** [comment]
Hmm I tested on full hd and 4k and worked in both cases. Are you doing the screenshot to find the region in the same mode you're playing in? Maybe playing in windowed mode?

If you want, you can attach a screenshot and I send you the region I think would fit :-D

**Comment by TheIngster** [comment]
Yeah I did the screenshot in the mode Im playing in and enetered in my values. Im not 100% sure what value should be set for the offsets. Thanks for the help. 

Screenshot attached as well as the values Ive set.

![screenshot-0002](https://user-images.githubusercontent.com/68303117/87606978-a4349d00-c73f-11ea-8dbb-b0c8be03aea7.png)
![image](https://user-images.githubusercontent.com/68303117/87606996-ad256e80-c73f-11ea-9c4e-1d33ffb80546.png)

**Comment by casid** [comment]
Can you try with 1696, 784, 842, 351? The offset looks about right. That's the distance between each slot.

**Comment by TheIngster** [comment]
Just tried with those settings and having the same problem. Attached a gif of where its selecting. Its just off a little bit. Tried in fullscreen and fullscreen windowed. Thanks again for taking the time. 
![stash](https://user-images.githubusercontent.com/68303117/87624350-ea532600-c76a-11ea-967b-444d703d5a85.gif)

**Comment by casid** [comment]
Hmm that's very weird!

Looks almost like the mouse coordinates have a slightly different scaling than the screen coordinates. I think your area is correct, since it detects all currency slots.

I could probably add another setting mouseClickOffset so that you could adjust it :-D

**Comment by TheIngster** [comment]
Good to know I didnt get the numbers wrong. 
If its an easy add then that would be great but dont stress if not. Either way, thanks for the help mate.
