### ISSUE TITLE
NullPointerException (null) error when launching .exe

### ISSUE THREAD

**Issue by coupdegrac3** [casid/poe-stash-buddy#4]
Hey,

ive downloaded the 0.4 release, when i start the poe-stash-buddy.exe i get the NullPointerException (null) error
![image](https://user-images.githubusercontent.com/59320545/126321100-e541e0c6-ccb6-49da-9642-3fd1c72d0b1e.png)

do i need something else installed for it to work or is the project not supported anymore?

regards
coup

**Comment by casid** [comment]
Hey, sorry I haven't used the stash buddy for a few years. The project is pretty much unmaintained by now.
